-- Schema for assessment wk2
create schema Assessment
go
-- Table Creation
drop table Assessment.Products
drop table Assessment.Customers
drop table Assessment.Orders

create table Assessment.Products (
	ID int not null primary key identity,
	Name nvarchar(100) not null,
	Price money not null
)

create table Assessment.Customers (
	ID int not null primary key identity,
	FirstName nvarchar(100) not null,
	LastName nvarchar(100) not null,
	CardNumber bigint unique not null
)

create table Assessment.Orders (
	ID int not null primary key identity,
	ProductID int not null foreign key references Assessment.Products (ID),
	CustomerID int not null foreign key references Assessment.Customers (ID)
)



-- Exercises
--		Add 3 entries to each table
insert into Assessment.Products (Name, Price) values
	('Plasma TV', 1000),
	 ('Xbox', 350),
	 ('Playstation',400)

insert into Assessment.Customers (FirstName, LastName, CardNumber) values
	 ('William', 'Craig', 1234567890000000),
	 ('Storm', 'Rubio', 9080706050403020),
	 ('Conrad', 'Troha', 1020304050607080)

insert into Assessment.Orders (ProductID, CustomerID) values
	(1,1),
	(2,2),
	(3,3)

select * from Assessment.Products
select * from Assessment.Customers
select * from Assessment.Orders

--		Add Product Iphone for 200

insert into Assessment.Products (Name, Price) values
	('IPhone',200)

--		Add Customer Tina Smith

insert into Assessment.Customers (FirstName, LastName, CardNumber) values
	('Tina', 'Smith', 1010101010101010)

--		Create Order for Tina Smith and IPhone

insert into Assessment.Orders (CustomerID, ProductID) values
	((select ID from Assessment.Customers where FirstName = 'Tina' and LastName = 'Smith'),
	 (select ID from Assessment.Products where Name = 'IPhone'))

--		Report all orders by Tina Smith

select c.FirstName, c.LastName, p.Name, p.Price from Assessment.Orders o 
		inner join Assessment.Customers c on c.ID = o.CustomerID
		inner join Assessment.Products p on p.ID = o.ProductID
		where c.FirstName = 'Tina' and c.LastName = 'Smith'

--		Report all revenure generated by IPhone

select p.Name, sum(p.Price) as Revanue from Assessment.Orders o
	inner join Assessment.Products p on p.ID = o.ProductID
	where p.Name = 'IPhone'
	group by p.Name

--		Change the price of IPhone to 250

update Assessment.Products set Price = 250 where Name = 'IPhone'
	